//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.0.23.0 (Newtonsoft.Json v10.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------





export interface Basic {
    name: string | undefined;
}

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.0.23.0 (Newtonsoft.Json v10.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------





export interface Complicated {
    name: string | undefined;
    date: number;
}

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.0.23.0 (Newtonsoft.Json v10.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------





export interface DiscriminatedUnionType_Basic {
    name: string | undefined;
}
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.0.23.0 (Newtonsoft.Json v10.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------





export interface DiscriminatedUnionType_Complicated {
    name: string | undefined;
    date: number;
}

export type DiscriminatedUnionType = DiscriminatedUnionType_Basic | DiscriminatedUnionType_Complicated
